/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Angazovanje;
import model.Predmet;
import model.Profesor;

/**
 *
 * @author Andrej
 */
public class AngazovanjeForma extends javax.swing.JFrame {

    private List<Profesor> listaProfesora = Controller.getInstance().ucitajProfesore();
    
    public AngazovanjeForma() {
        initComponents();
        ModelTabeleProfesor mtp = new ModelTabeleProfesor(listaProfesora);
        jTableProfesori.setModel(mtp);
        popuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBoxPredmeti = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAngazovanja = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProfesori = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonAngazovanja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxPredmeti1 = new javax.swing.JComboBox<>();
        jButtonDodaj = new javax.swing.JButton();

        jLabel5.setText("Predmet");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAngazovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAngazovanja);

        jTableProfesori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableProfesori);

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonAngazovanja.setText("Angazovanja");
        jButtonAngazovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngazovanjaActionPerformed(evt);
            }
        });

        jLabel6.setText("Predmet");

        jButtonDodaj.setText("Dodaj angazovanje");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAngazovanja)
                            .addComponent(jButtonObrisi))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxPredmeti1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAngazovanja, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxPredmeti1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jButtonDodaj)))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int red = jTableProfesori.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Niste selektovali red","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ModelTabeleProfesor mtp = (ModelTabeleProfesor) jTableProfesori.getModel();
        List<Profesor> lista = mtp.getListaProfesora();
        Profesor p = lista.get(red);
        boolean uspesno = Controller.getInstance().obrisiProfesora(p.getId());
        
        if(uspesno){
            JOptionPane.showMessageDialog(this, "USPESNO");
        }else{
            JOptionPane.showMessageDialog(this, "GRESKA");
        }
        
        osveziTabelu();
        
        
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonAngazovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngazovanjaActionPerformed
        
        List<Angazovanje> listaAngazovanja = Controller.getInstance().ucitajAngazovanja();
        List<Angazovanje> izabrani = new ArrayList<>();

        int red = jTableProfesori.getSelectedRow();
        if(red == -1){
            izabrani = listaAngazovanja;
        }else{
            Profesor p = listaProfesora.get(red);
            for(Angazovanje a: listaAngazovanja){
                if(a.getProfesorId() == p.getId()){
                    izabrani.add(a);
                }
            }
        }
        
        
        ModelTabeleAngazovanja mta = new ModelTabeleAngazovanja(izabrani);
        jTableAngazovanja.setModel(mta);
    }//GEN-LAST:event_jButtonAngazovanjaActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        
            
        int red = jTableProfesori.getSelectedRow();
        Predmet pre = (Predmet)jComboBoxPredmeti1.getSelectedItem();
        Profesor p = listaProfesora.get(red);
        
        boolean proveri = Controller.getInstance().proveriAngazovanje(p,pre);
        
        if(!proveri){
            JOptionPane.showMessageDialog(this, "Lose angazovanje","Upozorenje",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean uspesno = Controller.getInstance().unesiAngazovanje(p,pre);
        if(uspesno){
            JOptionPane.showMessageDialog(this, "Dodato angazovanje","Uspesno",JOptionPane.INFORMATION_MESSAGE);
        }
        Angazovanje a = new Angazovanje(0,p.getId(),pre.getId());
        ModelTabeleAngazovanja mta = (ModelTabeleAngazovanja) jTableAngazovanja.getModel();
        mta.dodajAngazovanje(a);
        
    }//GEN-LAST:event_jButtonDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AngazovanjeForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAngazovanja;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmeti;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmeti1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAngazovanja;
    private javax.swing.JTable jTableProfesori;
    // End of variables declaration//GEN-END:variables

    private void osveziTabelu() {
        
        List<Profesor> listaProfesora = Controller.getInstance().ucitajProfesore();
        ModelTabeleProfesor mtp = new ModelTabeleProfesor(listaProfesora);
        jTableProfesori.setModel(mtp);
    }

    private void popuniComboBox() {
         List<Predmet> listaPredmeta = Controller.getInstance().ucitajPredmete();
        for(Predmet p: listaPredmeta){
            jComboBoxPredmeti1.addItem(p);
        }
    }

    private void osvezi() {
        List<Angazovanje> listaAngazovanja = Controller.getInstance().ucitajAngazovanja();
        ModelTabeleAngazovanja mta = new ModelTabeleAngazovanja(listaAngazovanja);
        jTableAngazovanja.setModel(mta);
    }
}
